// Generated by CoffeeScript 1.3.3
(function() {
  var Game, app, fs, game, io, ioLib, num_players, players, port;

  ioLib = require("socket.io");

  fs = require('fs');

  Game = require("./game.js").Game;

  port = process.argv[2] || 3000;

  num_players = process.argv[3] || 2;

  app = require('http').createServer(function(req, res) {
    var file;
    file = null;
    if (req.url === "/") {
      file = '/index.html';
    } else {
      file = req.url;
    }
    return fs.readFile(__dirname + file, function(err, data) {
      if (err) {
        console.log(err);
      }
      res.writeHead(200);
      return res.end(data);
    });
  });

  io = ioLib.listen(app);

  io.set('log level', 1);

  io.set("transports", ["xhr-polling"]);

  io.set("polling duration", 10);

  app.listen(port);

  game = new Game(num_players);

  players = {};

  io.sockets.on('connection', function(socket) {
    var playerID;
    console.log('connection made');
    playerID = null;
    socket.emit('start', {
      state: game.getState(playerID)
    });
    socket.on('move', function(move) {
      console.log('move', move);
      if (!game.begun) {
        console.log("game has not begun");
        return;
      }
      if ((game.expectedTurn != null) && game.expectedTurn.playerID !== playerID) {
        console.log("it is not " + playerID + "'s turn");
        return;
      }
      if ((game.expectedTurn != null) && game.expectedTurn.type !== move.type) {
        console.log("expected move type " + game.expectedTurn.type + ", received " + move.type);
        return;
      }
      return game.makeMove(move, function() {
        var id, obj, _results;
        for (id in players) {
          obj = players[id];
          obj.socket.emit('state', {
            state: game.getState(id)
          });
        }
      });
    });
    socket.on('state', function(data) {
      return socket.emit('state', {
        state: game.getState(playerID)
      });
    });
    socket.on('join', function(data) {
      console.log('join', data);
      if (game.playerExists(data.playerID)) {
        console.log('name in use: ', data.playerID);
        return;
      }
      if (game.players.length >= game.playerLimit) {
        return;
      }
      console.log('player joining: ' + data.playerID);
      game.join(data.playerID, function() {
        playerID = data.playerID;
        players[data.playerID] = {
          'socket': socket,
          connected: true
        };
        socket.broadcast.emit('join', data);
        data.isme = true;
        return socket.emit('join', data);
      });
    });
    socket.on('disconnect', function() {
      console.log('player disconnected: ', playerID);
      playerID && (players[playerID].connected = false);
    });
  });

  game.on('update', function() {
    return io.sockets.emit('update');
  });

  game.on('start', function() {
    return io.sockets.emit('gameStart');
  });

  game.on('end', function() {
    console.log('game ended');
    return io.sockets.emit('end');
  });

}).call(this);
